
DAYS=d15	d14	d11	d10	d7	d6	d5	d4	d3	d2	d1

all: $(DAYS)

d1:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d2:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d3:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d4:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d5:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d6:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d7:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d10:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d11:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp

d14:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp

d15:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp