
DAYS=d3	d2	d1

all: $(DAYS)

d1:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d2:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp
d3:
	mkdir -p build
	g++ -Wall -pedantic -std=c++2a -o build/$@ $@.cpp











